name: Spring Boot CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # 3. Build (IMPORTANT: correct folder)
      - name: Build project
        working-directory: springbootexample
        run: mvn clean package -DskipTests

      # 4. Run tests
      - name: Run tests
        working-directory: springbootexample
        run: mvn test

      # 5. Upload JAR for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: springbootexample/target/*.jar
